export const elements = {
  sunFlare: document.getElementById("sun-flare"),
  cityName: document.querySelector(".weather-description"),
  temperature: document.getElementById("temperature"),
  feelsLike: document.getElementById("feels-like"),
  humidity: document.getElementById("humidity"),
  description: document.getElementById("description"),
  wind: document.getElementById("wind"),
  icon: document.getElementById("weather-icon"),
  message: document.querySelector(".error-message"),
  chartCanvas: document.getElementById("forecastChart"),
  favoriteDropdownToggle: document.querySelector(".favorite-toggle-btn"),
  favoriteDropdownList: document.querySelector(".favorite-dropdown-list"),
  addFavoriteBtn: document.querySelector(".favorite-btn"),
  searchInput: document.querySelector(".search-input"),
  searchBtn: document.querySelector(".search-btn"),
  cloudLayer: document.getElementById("cloud-layer"),
  particleLayer: document.getElementById("weather-particles"),
  uvBox: document.getElementById("uv-index"),
  //aqiBox: document.getElementById("air-quality"),
  cityTitle: document.getElementById("city-title"),
};
